# Generated by Django 4.1.2 on 2022-10-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.FloatField(default=0.0)),
                ('Maltodextrin', models.FloatField(default=0.0)),
                ('FlowRate', models.FloatField(default=0.0)),
                ('Yield', models.FloatField(blank=True, default=0.0)),
                ('MoistureContent', models.FloatField(blank=True, default=0.0)),
                ('ColorChange', models.FloatField(blank=True, default=0.0)),
                ('R', models.FloatField(blank=True, default=0.0, verbose_name='Wettability')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Data',
                'ordering': ['-date'],
            },
        ),
    ]
